apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: nginx-storage-class
  volumeMode: Filesystem
  volumeName: nginx-pv
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nginx-pv
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  storageClassName: nginx-storage-class
  claimRef:
    name: nginx-pvc
  local:
    path: /kube/nginx
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: NotIn
          values:
          - sample-text
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nginx-storage-class
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: nginx-pv
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 250m
            memory: 50Mi
      initContainers:
      - name: install
        image: busybox:latest
        command:
        - /bin/sh
        - -c
        - wget -O /usr/share/nginx/html/index.html http://info.cern.ch
        volumeMounts:
          - mountPath: /usr/share/nginx/html
            name: nginx-pv
      volumes:
      - name: nginx-pv
        persistentVolumeClaim:
          claimName: nginx-pv
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-lb
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      name: http
  type: LoadBalancer
---
